/**
 * OpsPlaybook — Scenarios & Troubleshooting Matrix
 * Stack: Vite/React + Express + Nginx + PM2 + Cloudflare
 */

export const opsLabScenarios = [
  {
    id: "deploy-new-version",
    title: "Deploy New Version",
    objective: "Pull the latest code, rebuild the frontend, and restart the application with zero downtime using PM2.",
    checklist: [
      "SSH into the production server",
      "Pull latest changes from main branch",
      "Install any new dependencies",
      "Build the Vite frontend",
      "Restart the app with PM2",
      "Verify the process is running",
    ],
    runbook: [
      "ssh deploy@app.example.com",
      "cd /var/www/myapp",
      "git pull origin main",
      "npm install --omit=dev",
      "npm run build",
      "pm2 restart myapp",
      "pm2 status",
    ],
  },
  {
    id: "rollback-failed-deploy",
    title: "Rollback Failed Deploy",
    objective: "A deploy broke production. Roll back to the previous working commit and restart the service immediately.",
    checklist: [
      "Identify the last known good commit",
      "Hard reset to that commit",
      "Rebuild the frontend",
      "Restart PM2",
      "Confirm the rollback is live",
    ],
    runbook: [
      "git log --oneline -5",
      "git reset --hard HEAD~1",
      "npm run build",
      "pm2 restart myapp",
      "pm2 logs myapp --lines 20",
    ],
  },
  {
    id: "nginx-reload",
    title: "Nginx Config Reload",
    objective: "Update the Nginx reverse proxy config and reload it without dropping active connections.",
    checklist: [
      "Edit the Nginx site config",
      "Test the config syntax",
      "Reload Nginx (not restart — no downtime)",
      "Verify the new config is active",
    ],
    runbook: [
      "sudo nano /etc/nginx/sites-available/myapp",
      "sudo nginx -t",
      "sudo systemctl reload nginx",
      "curl -I https://app.example.com",
    ],
    guards: {
      "sudo systemctl reload nginx": "sudo nginx -t",
    },
    failureMessages: {
      "sudo nginx -t": "💥 nginx: [emerg] invalid number of arguments in 'server_name' directive — config is broken. Nginx failed to reload. Site is DOWN. Fix the config and run `sudo nginx -t` before reloading.",
    },
  },
  {
    id: "pm2-crash-recovery",
    title: "PM2 Process Crash Recovery",
    objective: "The Node.js app crashed and PM2 errored out. Diagnose, fix, and bring it back up.",
    checklist: [
      "Check PM2 process list for error status",
      "Read the crash logs",
      "Delete the crashed process entry",
      "Start fresh with the ecosystem file",
      "Save PM2 state so it survives reboots",
    ],
    runbook: [
      "pm2 list",
      "pm2 logs myapp --err --lines 50",
      "pm2 delete myapp",
      "pm2 start ecosystem.config.js",
      "pm2 save",
    ],
    // Simulated crash output when user inspects logs — shows emoji SyntaxError
    commandOutputs: {
      "pm2 logs myapp --err --lines 50": [
        "0|myapp  | /var/www/myapp/src/routes/api.js:47",
        "0|myapp  |   const msg = \"✅ Deployment complete 🚀\";",
        "0|myapp  |                ^",
        "0|myapp  | SyntaxError: Invalid or unexpected token",
        "0|myapp  |     at wrapSafe (internal/modules/cjs/loader.js:915:16)",
        "0|myapp  |     at Module._compile (internal/modules/cjs/loader.js:963:27)",
        "0|myapp  | [PM2] App [myapp] with id [0] restarting... (restart #47)",
        "# Emoji in backend source code — Node.js can't parse them without --experimental-vm-modules",
        "# Fix: remove emoji from server-side JS, or add BOM + utf-8 pragma to the file",
      ],
    },
  },
  {
    id: "ssl-certificate-renewal",
    title: "SSL Certificate Renewal",
    objective: "The SSL certificate is expiring in 7 days. Renew it with Certbot and reload Nginx.",
    checklist: [
      "Check certificate expiry date",
      "Run Certbot renewal",
      "Verify the new cert is installed",
      "Reload Nginx to pick up the new cert",
      "Confirm HTTPS is working",
    ],
    runbook: [
      "sudo certbot certificates",
      "sudo certbot renew --dry-run",
      "sudo certbot renew",
      "sudo systemctl reload nginx",
      "curl -vI https://app.example.com 2>&1 | grep expire",
    ],
  },
  {
    id: "cloudflare-cache-purge",
    title: "Cloudflare Cache Purge",
    objective: "Users are seeing stale assets after a deploy. Purge the Cloudflare cache via the API.",
    checklist: [
      "Identify the Cloudflare Zone ID",
      "Call the purge everything API endpoint",
      "Verify assets are being served fresh",
    ],
    runbook: [
      "export CF_ZONE=your_zone_id",
      "export CF_TOKEN=your_api_token",
      'curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE/purge_cache" -H "Authorization: Bearer $CF_TOKEN" -H "Content-Type: application/json" --data \'{"purge_everything":true}\'',
      "curl -I https://app.example.com/assets/index.js | grep cf-cache-status",
    ],
  },
  {
    id: "memory-leak-diagnosis",
    title: "Memory Leak Diagnosis",
    objective: "The Express app is consuming 2 GB of RAM and slowing down. Identify the leak and restart safely.",
    checklist: [
      "Check current memory usage with PM2",
      "Inspect OS-level memory stats",
      "Generate a heap snapshot",
      "Restart the process to restore service",
      "Set a memory limit in PM2 to auto-restart on threshold",
    ],
    runbook: [
      "pm2 monit",
      "free -h",
      "node --inspect server.js &",
      "pm2 restart myapp",
      "pm2 stop myapp",
      'pm2 start ecosystem.config.js --max-memory-restart 512M',
    ],
  },
  {
    id: "db-connection-failure",
    title: "Database Connection Failure",
    objective: "The app is returning 500 errors. The logs show database connection timeouts. Diagnose and restore connectivity.",
    checklist: [
      "Check app logs for the specific error",
      "Test database port is reachable",
      "Verify the DB service is running",
      "Check the .env connection string",
      "Restart the app after confirming DB is up",
    ],
    runbook: [
      "pm2 logs myapp --err --lines 30",
      "nc -zv db.example.com 5432",
      "sudo systemctl status postgresql",
      "cat /var/www/myapp/.env | grep DATABASE_URL",
      "pm2 restart myapp",
    ],
  },
  {
    id: "env-var-update",
    title: "Update Environment Variable in Production",
    objective: "A third-party API key has been rotated. Update the .env file and reload the app without a full redeploy.",
    checklist: [
      "SSH into the server",
      "Edit the .env file safely",
      "Confirm the new value is set",
      "Restart PM2 to pick up the change",
      "Tail logs to confirm no auth errors",
    ],
    runbook: [
      "ssh deploy@app.example.com",
      "cd /var/www/myapp",
      "nano .env",
      "grep API_KEY .env",
      "pm2 restart myapp",
      "pm2 logs myapp --lines 20",
    ],
  },
  {
    id: "ghost-asset-incident",
    title: "🔴 The 70-Hour Bug",
    objective: "White Screen of Death after deploy. Browser console: GET 404 /assets/index-A1B2C3D4.js. The file doesn't exist in dist/. Find why and fix it.",
    incident: "⚠ INCIDENT: Users report blank white page after latest deploy. Nginx logs show 404 on all JS/CSS assets. The app process is running. No errors in PM2.",
    checklist: [
      "Check what asset hashes Nginx is currently serving via the index.html",
      "List actual files in dist/assets to find the hash mismatch",
      "Identify why the build wasn't completed or points to the wrong dist",
      "Rebuild the frontend with npm run build",
      "Restart PM2 to pick up the new dist",
      "Test Nginx config before reloading",
      "Reload Nginx",
      "Purge Cloudflare cache (stale HTML still points to old hashes at CDN edge)",
      "Verify the site loads correctly",
    ],
    runbook: [
      "curl -s https://app.example.com | grep 'src='",
      "ls dist/assets/",
      "cat nginx.conf | grep root",
      "npm run build",
      "pm2 restart myapp",
      "sudo nginx -t",
      "sudo systemctl reload nginx",
      "cloudflare-cli purge --zone winlab.io --all",
      "curl -I https://app.example.com | grep -E 'cf-cache-status|200'",
    ],
    // Steps that MUST be completed before others (skip = failure)
    guards: {
      // Must run nginx -t before reload
      "sudo systemctl reload nginx": "sudo nginx -t",
      // Must purge CF before final verification
      "curl -I https://app.example.com | grep -E 'cf-cache-status|200'": "cloudflare-cli purge --zone winlab.io --all",
    },
    failureMessages: {
      "sudo nginx -t": "💥 nginx: [emerg] unexpected end of file — you skipped the syntax check. Nginx config is now broken. Run `sudo nginx -t` first.",
      "cloudflare-cli purge --zone winlab.io --all": "⚠ Site loads on direct hit but Cloudflare edge still serves old index.html pointing to A1B2C3D4. Users on CDN still see blank page.",
    },
    solvedMessage: '✅ INCIDENT SOLVED.\n"Hai domato l\'Hash di Vite. Questo bug ha fatto piangere ingegneri con 10 anni di esperienza. La discrepanza tra build e distribuzione è il motivo per cui il DevOps esiste. Benvenuto nel club dei sopravvissuti."',
  },
  {
    id: "disk-full-recovery",
    title: "Disk Full — Emergency Recovery",
    objective: "The server disk is at 100%. The app is failing to write logs and crashes on startup. Free up space fast.",
    checklist: [
      "Check disk usage by partition",
      "Find the largest directories",
      "Clear PM2 logs",
      "Remove old build artifacts",
      "Verify free space restored",
      "Restart the app",
    ],
    runbook: [
      "df -h",
      "du -sh /var/www/myapp/* | sort -rh | head -10",
      "pm2 flush",
      "rm -rf /var/www/myapp/dist_old",
      "df -h",
      "pm2 restart myapp",
    ],
  },
  // ── Docker / Kubernetes / CI-CD ──────────────────────────────────────────
  {
    id: "docker-container-crash",
    title: "Docker Container Crash Loop",
    objective: "A container keeps restarting every 30 seconds. Diagnose the root cause and bring it back to a healthy state.",
    incident: "⚠ INCIDENT: Monitoring shows myapp container in restart loop. Uptime < 60s. Users getting 502.",
    checklist: [
      "Check which containers are running and their status",
      "Read the container crash logs",
      "Inspect the container environment variables",
      "Fix the broken .env and redeploy the container",
      "Verify the container is stable",
    ],
    runbook: [
      "docker ps -a",
      "docker logs myapp --tail 50",
      "docker inspect myapp | grep -A5 Env",
      "docker rm myapp && docker run -d --name myapp --env-file .env -p 3001:3001 myapp:latest",
      "docker ps",
    ],
    commandOutputs: {
      "docker ps -a": [
        "CONTAINER ID   IMAGE          COMMAND       CREATED         STATUS                       NAMES",
        "a1b2c3d4e5f6   myapp:latest   'node srv'    3 minutes ago   Restarting (1) 18 secs ago   myapp",
        "b2c3d4e5f6a1   nginx:alpine   '/docker-e'   2 hours ago     Up 2 hours                   nginx-proxy",
        "# myapp in Restarting loop — exit code 1",
      ],
      "docker logs myapp --tail 50": [
        "Error: Cannot find module '/app/node_modules/.bin/dotenv'",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:746:27)",
        "Error: Missing required env var: DATABASE_URL",
        "    at validateEnv (/app/src/config.js:12:11)",
        "# Root cause: .env file not mounted — container starts, fails immediately, Docker restarts it",
      ],
      "docker inspect myapp | grep -A5 Env": [
        '"Env": [',
        '    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",',
        '    "NODE_ENV=production"',
        "],",
        "# DATABASE_URL is MISSING from environment",
      ],
      "docker rm myapp && docker run -d --name myapp --env-file .env -p 3001:3001 myapp:latest": [
        "myapp",
        "7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c",
      ],
      "docker ps": [
        "CONTAINER ID   IMAGE          COMMAND       CREATED        STATUS         NAMES",
        "7f8a9b0c1d2e   myapp:latest   'node srv'    5 seconds ago  Up 4 seconds   myapp",
        "b2c3d4e5f6a1   nginx:alpine   '/docker-e'   2 hours ago    Up 2 hours     nginx-proxy",
      ],
    },
    solvedMessage: "✅ Container stabilised. Root cause: missing --env-file mount. Always use docker inspect to verify env vars before debugging app code.",
  },
  {
    id: "k8s-crashloop",
    title: "Kubernetes CrashLoopBackOff",
    objective: "A production pod is in CrashLoopBackOff. Roll back to the last working image and restore service.",
    incident: "⚠ INCIDENT: PagerDuty — pod myapp-6d4f9b in CrashLoopBackOff since last deploy 14 minutes ago.",
    checklist: [
      "List pods and confirm the crash state",
      "Describe the pod to see events and error",
      "Read previous container logs (before last restart)",
      "Roll back the deployment to the previous image",
      "Confirm the rollout is healthy",
    ],
    runbook: [
      "kubectl get pods -n production",
      "kubectl describe pod -n production -l app=myapp",
      "kubectl logs -n production -l app=myapp --previous",
      "kubectl rollout undo deployment/myapp -n production",
      "kubectl rollout status deployment/myapp -n production",
    ],
    commandOutputs: {
      "kubectl get pods -n production": [
        "NAME                     READY   STATUS             RESTARTS   AGE",
        "myapp-6d4f9b-xk2p9       0/1     CrashLoopBackOff   8          14m",
        "myapp-6d4f9b-nw8qt       0/1     CrashLoopBackOff   8          14m",
        "redis-7c9f8b-m3kj2       1/1     Running            0          2d",
        "postgres-8b4d7c-p9lm1    1/1     Running            0          2d",
      ],
      "kubectl describe pod -n production -l app=myapp": [
        "Events:",
        "  Warning  BackOff    2m    kubelet  Back-off restarting failed container",
        "  Warning  Failed     14m   kubelet  Error: failed to create containerd task:",
        "           failed to create shim task: OCI runtime create failed:",
        "           container_linux.go:380: starting container process caused:",
        "           process_linux.go:545: container init caused:",
        "           rootfs_linux.go:76: mounting .env over /app/.env caused:",
        "           mount through procfd: not a directory: unknown",
        "# ConfigMap mounted as file but path points to a directory — wrong volumeMount",
      ],
      "kubectl logs -n production -l app=myapp --previous": [
        "Error: ENOENT: no such file or directory, open '/app/.env'",
        "    at Object.openSync (fs.js:462:3)",
        "    at Object.readFileSync (fs.js:364:35)",
        "    at Object.<anonymous> (/app/src/config.js:3:22)",
        "# .env ConfigMap not loading — volumeMount subPath misconfigured",
      ],
      "kubectl rollout undo deployment/myapp -n production": [
        'deployment.apps/myapp rolled back',
      ],
      "kubectl rollout status deployment/myapp -n production": [
        "Waiting for deployment 'myapp' rollout to finish: 0 of 2 updated replicas are available...",
        "Waiting for deployment 'myapp' rollout to finish: 1 of 2 updated replicas are available...",
        "deployment 'myapp' successfully rolled out",
      ],
    },
    solvedMessage: "✅ Rollback complete. Root cause: volumeMount subPath misconfigured in last deploy — ConfigMap mounted as directory instead of file. Fix the Helm values before redeploying.",
  },
  {
    id: "redis-oom",
    title: "Redis OOM — Cache Eviction Storm",
    objective: "Redis is evicting keys aggressively and the app is seeing cache miss spikes. Diagnose memory pressure and tune the eviction policy.",
    checklist: [
      "Check Redis is reachable and read memory stats",
      "Identify the current eviction policy",
      "Check which keys are consuming the most memory",
      "Set a sensible maxmemory limit",
      "Switch to allkeys-lru eviction policy",
      "Verify the change is active",
    ],
    runbook: [
      "redis-cli ping",
      "redis-cli info memory | grep -E 'used_memory_human|maxmemory_human|evicted_keys'",
      "redis-cli config get maxmemory-policy",
      "redis-cli config set maxmemory 512mb",
      "redis-cli config set maxmemory-policy allkeys-lru",
      "redis-cli info memory | grep -E 'used_memory_human|maxmemory_human|maxmemory_policy'",
    ],
    commandOutputs: {
      "redis-cli ping": ["PONG"],
      "redis-cli info memory | grep -E 'used_memory_human|maxmemory_human|evicted_keys'": [
        "used_memory_human:1.98G",
        "maxmemory_human:0B          ← no limit set — Redis using ALL available RAM",
        "evicted_keys:284710         ← 284k keys evicted in last hour",
      ],
      "redis-cli config get maxmemory-policy": [
        "1) \"maxmemory-policy\"",
        "2) \"noeviction\"         ← with no maxmemory, this causes OOM errors instead of eviction",
      ],
      "redis-cli config set maxmemory 512mb": ["OK"],
      "redis-cli config set maxmemory-policy allkeys-lru": ["OK"],
      "redis-cli info memory | grep -E 'used_memory_human|maxmemory_human|maxmemory_policy'": [
        "used_memory_human:487.34M",
        "maxmemory_human:512.00M",
        "# maxmemory_policy: allkeys-lru — LRU eviction active, OOM risk eliminated",
      ],
    },
    solvedMessage: "✅ Redis tuned. The unlimited memory + noeviction combo is a ticking bomb in production. Always set maxmemory + allkeys-lru for a cache workload.",
  },
  {
    id: "blue-green-deploy",
    title: "Zero-Downtime Blue-Green Deploy",
    objective: "Deploy v2 of the app alongside v1, run smoke tests, then switch Nginx upstream — zero dropped requests.",
    checklist: [
      "Build and start the new v2 container on port 3002",
      "Smoke test v2 directly before any traffic switch",
      "Update the Nginx upstream to point to v2",
      "Test Nginx config before reloading",
      "Reload Nginx — traffic switches instantly",
      "Stop the old v1 container",
      "Verify the live site is running v2",
    ],
    runbook: [
      "docker run -d --name myapp-v2 --env-file .env -p 3002:3001 myapp:v2",
      "curl -s http://localhost:3002/health | grep ok",
      "nano /etc/nginx/sites-available/myapp",
      "sudo nginx -t",
      "sudo systemctl reload nginx",
      "docker stop myapp-v1 && docker rm myapp-v1",
      "curl -s https://app.example.com/api/version",
    ],
    guards: {
      "sudo systemctl reload nginx": "sudo nginx -t",
    },
    failureMessages: {
      "sudo nginx -t": "💥 nginx config broken — upstream points to wrong port. Nginx reload aborted. v1 still live.",
    },
    commandOutputs: {
      "docker run -d --name myapp-v2 --env-file .env -p 3002:3001 myapp:v2": [
        "9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d",
      ],
      "curl -s http://localhost:3002/health | grep ok": [
        '{"status":"ok","version":"2.1.0","db":"connected"}',
      ],
      "docker stop myapp-v1 && docker rm myapp-v1": [
        "myapp-v1",
        "myapp-v1",
      ],
      "curl -s https://app.example.com/api/version": [
        '{"version":"2.1.0","env":"production"}',
      ],
    },
    solvedMessage: "✅ Blue-green complete. Zero downtime. v2 live. v1 cleaned up. This is the correct way to deploy without a load balancer health check window.",
  },
  {
    id: "cicd-broken-pipeline",
    title: "CI/CD Pipeline — Missing Secret",
    objective: "The GitHub Actions deploy workflow is failing at the SSH step. Find the missing secret and restore automated deploys.",
    incident: "⚠ INCIDENT: Last 3 deploys via GitHub Actions failed. Engineers are deploying manually. Tech debt accumulating.",
    checklist: [
      "Read the workflow run error from the Actions log",
      "Identify which secret is missing",
      "Verify the SSH key is present on the server",
      "Add the secret to the GitHub repo",
      "Re-run the failed workflow",
      "Confirm the deployment succeeded",
    ],
    runbook: [
      "gh run list --workflow=deploy.yml --limit 5",
      "gh run view --log-failed",
      "cat ~/.ssh/authorized_keys | grep deploy",
      "gh secret set DEPLOY_SSH_KEY < ~/.ssh/id_ed25519",
      "gh run rerun --failed",
      "gh run watch",
    ],
    commandOutputs: {
      "gh run list --workflow=deploy.yml --limit 5": [
        "STATUS  TITLE                          WORKFLOW    BRANCH  EVENT   ID",
        "✗ fail  deploy: bump version to 2.1.0  deploy.yml  main    push    9812340",
        "✗ fail  deploy: fix redis config       deploy.yml  main    push    9812201",
        "✗ fail  deploy: update deps            deploy.yml  main    push    9811988",
        "✓ pass  deploy: add rate limiting      deploy.yml  main    push    9807442",
      ],
      "gh run view --log-failed": [
        "Run appleboy/ssh-action@v1.0.0",
        "  err: ssh: handshake failed: ssh: unable to authenticate,",
        "  err: attempted methods [none publickey], no supported methods remain",
        "  err: dial tcp 203.0.113.10:22: connection refused",
        "# Secret DEPLOY_SSH_KEY is empty or missing from repo secrets",
      ],
      "cat ~/.ssh/authorized_keys | grep deploy": [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... deploy@github-actions",
        "# Key IS on server — secret was deleted from GitHub repo secrets",
      ],
      "gh secret set DEPLOY_SSH_KEY < ~/.ssh/id_ed25519": [
        "✓ Set Actions secret DEPLOY_SSH_KEY for Linkq1-crypto/winlab",
      ],
      "gh run rerun --failed": [
        "✓ Requested rerun of run 9812340",
      ],
      "gh run watch": [
        "Refreshing run status every 3 seconds. Press Ctrl+C to quit.",
        "",
        "✓ deploy: bump version to 2.1.0 · deploy.yml",
        "Triggered via push about 1 minute ago",
        "",
        "JOBS",
        "✓ build (18s)",
        "✓ deploy (31s)",
        "",
        "✓ Run deploy.yml completed with 'success'",
      ],
    },
    solvedMessage: "✅ CI/CD restored. Root cause: DEPLOY_SSH_KEY secret was accidentally deleted during repo settings cleanup. Automate secret rotation and add secret-existence checks to your workflow.",
  },
  {
    id: "k8s-node-notready",
    title: "Kubernetes Node NotReady",
    objective: "One cluster node is NotReady and pods are being evicted. Find the root cause and restore the node.",
    incident: "⚠ INCIDENT: k8s-node-02 NotReady for 8 minutes. 12 pods evicted. Cluster running at reduced capacity.",
    checklist: [
      "Check node status and identify the NotReady node",
      "Describe the node to read conditions and events",
      "SSH into the failing node and check kubelet",
      "Check available disk — node may have disk pressure",
      "Clean up evicted pod images to free disk",
      "Restart kubelet and verify node rejoins",
    ],
    runbook: [
      "kubectl get nodes",
      "kubectl describe node k8s-node-02",
      "ssh admin@k8s-node-02 'systemctl status kubelet'",
      "ssh admin@k8s-node-02 'df -h /var/lib/docker'",
      "ssh admin@k8s-node-02 'docker system prune -f'",
      "ssh admin@k8s-node-02 'systemctl restart kubelet'",
    ],
    commandOutputs: {
      "kubectl get nodes": [
        "NAME            STATUS     ROLES           AGE   VERSION",
        "k8s-master-01   Ready      control-plane   42d   v1.28.4",
        "k8s-node-01     Ready      worker          42d   v1.28.4",
        "k8s-node-02     NotReady   worker          42d   v1.28.4   ← PROBLEM",
        "k8s-node-03     Ready      worker          42d   v1.28.4",
      ],
      "kubectl describe node k8s-node-02": [
        "Conditions:",
        "  Type                 Status  Reason",
        "  ----                 ------  ------",
        "  MemoryPressure       False   KubeletHasSufficientMemory",
        "  DiskPressure         True    KubeletHasDiskPressure     ← ROOT CAUSE",
        "  PIDPressure          False   KubeletHasSufficientPID",
        "  Ready                False   KubeletNotReady",
        "",
        "Events:",
        "  Warning  EvictionThresholdMet  3m  kubelet  Attempting to reclaim ephemeral-storage",
        "  Warning  NodeNotReady          2m  kubelet  Node condition DiskPressure is True",
      ],
      "ssh admin@k8s-node-02 'systemctl status kubelet'": [
        "● kubelet.service — Kubernetes Kubelet",
        "   Active: active (running)",
        "   Warning: eviction manager: attempting to reclaim disk (imagefs)",
        "   Warning: disk pressure observed — kubelet marking node NotReady",
      ],
      "ssh admin@k8s-node-02 'df -h /var/lib/docker'": [
        "Filesystem      Size  Used Avail Use% Mounted on",
        "/dev/sdb1        50G   49G  200M  99% /var/lib/docker   ← 99% full",
        "# Accumulated dangling images and stopped container layers",
      ],
      "ssh admin@k8s-node-02 'docker system prune -f'": [
        "Deleted Containers: 47",
        "Deleted Images: 23",
        "Total reclaimed space: 18.4GB",
      ],
      "ssh admin@k8s-node-02 'systemctl restart kubelet'": [
        "# kubelet restarted — DiskPressure condition should clear in ~30 seconds",
      ],
    },
    solvedMessage: "✅ Node k8s-node-02 back to Ready. Root cause: accumulated Docker images over 42 days filled /var/lib/docker. Add a cron job: docker system prune -f --filter until=168h and set imagefs.available eviction threshold.",
  },
];

export const troubleshootingMatrix = [
  {
    symptom: "502 Bad Gateway from Nginx",
    cause: "Node.js / PM2 process is down or not listening on the expected port",
    fix: "Run `pm2 list` — if status is errored, check `pm2 logs` then `pm2 restart myapp`",
  },
  {
    symptom: "504 Gateway Timeout",
    cause: "App is running but responding too slowly — DB query, external API, or CPU spike",
    fix: "Check `pm2 monit` for CPU/RAM. Run `pm2 logs` to find the slow endpoint. Add a timeout or optimize the query.",
  },
  {
    symptom: "Assets returning 404 after deploy",
    cause: "Vite build not run — old `dist/` folder or missing build step",
    fix: "Run `npm run build` then `pm2 restart myapp`. Check Nginx root path points to `dist/`.",
  },
  {
    symptom: "CSS/JS served with wrong MIME type (text/html)",
    cause: "Nginx SPA fallback is intercepting static asset requests",
    fix: "Add `try_files $uri $uri/ =404` for `/assets/` location before the SPA catch-all in nginx config. Reload Nginx.",
  },
  {
    symptom: "App crashes on startup after git pull",
    cause: "New dependency not installed or breaking change in package.json",
    fix: "Run `npm install`. Check `pm2 logs myapp --err` for the exact module error.",
  },
  {
    symptom: "Cloudflare showing stale content after deploy",
    cause: "Cloudflare cache not purged — serving old assets from edge",
    fix: "Purge via Cloudflare dashboard or API. Add cache-busting headers or use Vite content hashing.",
  },
  {
    symptom: "SSL certificate error in browser",
    cause: "Cert expired or Nginx not reloaded after renewal",
    fix: "Run `sudo certbot renew` then `sudo systemctl reload nginx`. Verify with `curl -vI https://yourdomain.com`.",
  },
  {
    symptom: "PM2 process restarts in a loop",
    cause: "App crashes immediately on start — usually a missing .env var or port already in use",
    fix: "Run `pm2 logs myapp --err`. Check `.env` exists and all required vars are set. Check `lsof -i :3001` for port conflict.",
  },
  {
    symptom: "Environment variables not picked up",
    cause: "PM2 caching old env or .env file not reloaded",
    fix: "Run `pm2 restart myapp --update-env` or `pm2 delete myapp && pm2 start ecosystem.config.js`.",
  },
  {
    symptom: "High memory usage / OOM kill",
    cause: "Memory leak in Express routes, unclosed DB connections, or large in-memory caches",
    fix: "Set `--max-memory-restart 512M` in PM2. Profile with `node --inspect`. Check for missing `await` on DB queries.",
  },
  {
    symptom: "Database connection timeout",
    cause: "DB server down, wrong host/port in .env, or connection pool exhausted",
    fix: "Run `nc -zv db.host 5432`. Check `DATABASE_URL` in .env. Restart DB service. Increase pool size in Prisma/pg config.",
  },
  {
    symptom: "Disk full — app fails to start",
    cause: "Logs, old builds, or node_modules filling the disk",
    fix: "Run `df -h` and `du -sh /* | sort -rh`. Clear with `pm2 flush`, delete old `dist_*` folders, prune `node_modules`.",
  },
];
